server:
  port: 9000

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
    producer:
      bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:h2:mem:citydb
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console.enabled: true

app:
  services:
    dictionary:
      city:
        url: https://cityservice.mocklab.io/v1/cities
        user: admin
        password: admin

